# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy

class CrawlerItem(scrapy.Item):
    # define the fields for your item here like:
    
    ID = scrapy.Field()
    ptype = scrapy.Field()
    productcode = scrapy.Field()
    title = scrapy.Field()
    public = scrapy.Field()
    featured = scrapy.Field()
    displayInCat = scrapy.Field()
    shortDes = scrapy.Field()
    longDes = scrapy.Field()
    promoStartDate = scrapy.Field()
    promoEndDate = scrapy.Field()
    taxStatus = scrapy.Field()
    tax = scrapy.Field()
    instock = scrapy.Field()
    houseware = scrapy.Field()
    limited = scrapy.Field()
    bookavailable = scrapy.Field()
    privatesale = scrapy.Field()
    weight = scrapy.Field()
    longwidth = scrapy.Field()
    thinwidth = scrapy.Field()
    height = scrapy.Field()
    commentable = scrapy.Field()
    paymentnote = scrapy.Field()
    saleprice = scrapy.Field()
    price = scrapy.Field()
    category = scrapy.Field()
    tags = scrapy.Field()
    shippingclass = scrapy.Field()
    image = scrapy.Field()
    downloadavailable = scrapy.Field()
    downloadenddate = scrapy.Field()
    org = scrapy.Field()
    group = scrapy.Field()
    upsell = scrapy.Field()
    bancheo = scrapy.Field()
    urlngoai = scrapy.Field()
    content = scrapy.Field()
    location = scrapy.Field()
    field1name = scrapy.Field()
    field1value = scrapy.Field()
    field1display = scrapy.Field()
    field1global = scrapy.Field()
    field2name = scrapy.Field()
    field2value = scrapy.Field()
    field2display = scrapy.Field()
    field2global = scrapy.Field()
    field3name = scrapy.Field()
    field3value = scrapy.Field()
    field3display = scrapy.Field()
    field3global = scrapy.Field()
    field4name = scrapy.Field()
    field4value = scrapy.Field()
    field4display = scrapy.Field()
    field4global = scrapy.Field()
    field5name = scrapy.Field()
    field5value = scrapy.Field()
    field5display = scrapy.Field()
    field5global = scrapy.Field()
    field6name = scrapy.Field()
    field6value = scrapy.Field()
    field6display = scrapy.Field()
    field6global = scrapy.Field()
    meta1 = scrapy.Field()
    meta2 = scrapy.Field()
    meta3 = scrapy.Field()
    meta4 = scrapy.Field()
    meta5 = scrapy.Field()